version: '3.3'
services:
  app:
    image: 1dd372497e4f
    container_name: boilerplate
    volumes:
      - ./:/home/www
    networks:
      - app-network

  webserver:
    image: 3ef8483d22e1
    container_name: boilerplate_nginx
    tty: true
    ports:
      - "9000:80"
    volumes:
      - ./:/home/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
